### PR TITLE
[JRO] Update gemspec

### PR DESCRIPTION
**Pull request by jayroh**
1. Add Gleb to authors & emails
2. Bump rails dependency to 4.1.0+

### CODE REVIEW

**Comment by glebm** [comment]
:+1:

**Comment by glebm** [comment]
Everyone always misspells my last name, thanks for getting it right! :smile:

**Comment by jayroh** [comment]
@glebm, also ->

```console
➜  thredded git:(jro-update-gemspec-authors) gem owner --add glex.spb@*****.com thredded
Owner added successfully.
...
```

**Comment by jayroh** [comment]
> Everyone always misspells my last name, thanks for getting it right!

Ha! I have the same problem. The whole "I before E" thing messes everything up

**Pull request merged**
