### PR TITLE
Redesign navigation

### PR DESCRIPTION
**Pull request by glebm**
| Embedded | Standalone |
| -------------- | -------------- |
| nav-desktop |  nav-standalone |
| nav-mobile | nav-mobile-standalone |

Fixed semantics:

* Private Messages moved to user nav.
* Search moved to main nav.

UI redesign on desktop and mobile

### CODE REVIEW

**Comment by glebm** [comment]
I've made a couple of amendments since taking the desktop screenshots, they look a tiny bit different now.

**Comment by jayroh** [comment]
Oh yeah, I definitely like this.

**Comment by jayroh** [comment]
Weird - just pushed these changes to production and things look a little off.

https://thredded.org/thredded/

**Comment by glebm** [comment]
@jayroh I'll have a look later tonight

**Comment by jayroh** [comment]
Sounds good Gleb. I might investigate too and see what I can find :). Save you some trouble.

**Comment by glebm** [comment]
The icons just need to be precompiled. I'll push a fix when I get back home in a couple of hours.

**Pull request merged**
