### PR TITLE
Config whitelist & filters

### PR DESCRIPTION
**Pull request by lawso017**
In order to get Thredded working with the basecamp/trix editor, I had to make the following two changes:

1. Since I'm now storing html content, I needed to remove the BBContent pipeline filter -- it was clobbering the img tags inside links. So I moved the list of content_pipeline_filters to the initializer.

2. Since Trix stores uploaded images as img elements inside a figure tag nested within a link, I needed to broaden the whitelist elements to allow figure tags (and figcaption). So I moved the whitelist elements to the initializer as well.

Not sure if this is a direction you'd want to go, but thought I'd pass it on.

Thanks!

### CODE REVIEW

**Comment by glebm** [comment]
Moving these to the initializer doesn't make it much different from having them as the constants on the PostCommon class. Neither are very modular.

What I'd like to have in the future is a `ContentFormatter` class instead of having this functionality in `PostCommon`. Then the user can monkey-patch/configure the aspects of the default `ContentFormatter` or even use a different one.

Meanwhile:
* `figure` and `figcaption` should be whitelisted by default. 
*  You can remove the BBContent filter by reassigning the constant in the initializer.

**Comment by jayroh** [comment]
Would agree on `figure` and `figcaption`.  Also +1 on the ContentFormatter class. The responsibility should belong to another class. They're a little too tightly coupled now.

**Comment by lawso017** [comment]
Thanks, that makes sense. ContentFormatter sounds great.

This may be a dumb question, but how do you recommend reassigning the constant in the initializer? I'm not familiar with that technique.

**Comment by glebm** [comment]
@lawso017 Sorry, it's not as simple as I thought it was, but the good news is that I've implemented the `ContentFormatter` in #321 so once that's merged it will be very easy to configure: https://github.com/thredded/thredded/pull/321/files#diff-d24aa57ddf38369b21abef6c31f43cae.

**Pull request closed without merging**
