### PR TITLE
Allow customizing first messageboard post

### PR DESCRIPTION
**Pull request by metalelf0**
This commit allows customizing the first messageboard post content and topic title by setting the following I18n keys:

- `thredded.topics.first_of_messageboard.title`
- `thredded.posts.first_of_messageboard.content`

The current english text has been copied over in all the locale files to keep the current behaviour.

Note: if [this PR](https://github.com/thredded/thredded/pull/669) is merged before of this, it will break the build, as the italian translation I provided in the other PR doesn't include the new keys mentioned above. Let me know if you need the translation.

### CODE REVIEW

**Comment by glebm** [comment]
Thanks!

> Note: if this PR is merged before of this, it will break the build, as the italian translation I provided in the other PR doesn't include the new keys mentioned above. Let me know if you need the translation.

The other PR is now merged!

**Comment by metalelf0** [comment]
@glebm ok, I fixed labels as requested and added italian translations for the missing keys. Let me know if there is something left to fix :)

**Comment by glebm** [comment]
Thanks!

**Comment by metalelf0** [comment]
Oops I just noticed I forgot to add Italian to the list of languages in the readme file.

**Pull request merged**
