### PR TITLE
Switch to RailsGravatar

### PR DESCRIPTION
**Pull request by rickychilcott**
This addresses #880 which is a concern about relying on the rb-gravatar gem, which has been GPLed in https://github.com/sn/ruby-gravatar/commit/5a1225c58f9363e66daae01698fcefc7d4f697b3 We _could_ peg our dependency on an older version of the gem, but it might be better to rely on a gem that is guaranteed to not be GPLed.

As such, I created a gem called [RailsGravatar](https://github.com/mission-met/rails_gravatar) which has a very similar API but changes some of the internals to better output rails tags (using `ActionView` helpers) and wrote a comprehensive test suite. The most important part is that it's MIT licensed and has no concerns about it being GPLed.

### CODE REVIEW

**Comment by glebm** [comment]
Thanks!

**Comment by glebm** [comment]
Looks like this isn't working correctly (CI failing)

The 3rd argument to `rb-gravatar` was `'mm'` but RailsGravatar expects a URL?

Can you please send a PR fixing this?

**Comment by glebm** [comment]
Looking at the source, it's not the `fallback_image_url`; not sure what the issue is

**Comment by glebm** [comment]
Example failing job https://travis-ci.org/github/thredded/thredded/jobs/766574511

Error:

```
   Failure/Error: <%= image_tag post.avatar_url, class: 'thredded--post--avatar' if post.user %>

      ActionView::Template::Error:

        nil is not a valid asset source
```

**Comment by timdiggins** [comment]
@rickychilcott we can't reopen this PR because it was merged once, but can you open another PR for this when you're ready?

**Pull request merged**
