### PR TITLE
Updated the 'signed_in?' method to accept an unused, optional 'scope' parameter…

### PR DESCRIPTION
**Pull request by pak9rabid**
…, to make it compatible with the devise_security_extension gem

### CODE REVIEW

**Comment by glebm** [comment]
The `signed_in?` method is a method only used by Thredded controllers. How exactly does it make it compatible with that gem?

**Comment by pak9rabid** [comment]
From what I can tell, devise_security_extensions is calling the version provided by thredded's application_controller.rb, and since it doesn't support the 'scope' argument that it's passing in, the app crashes with a "wrong number of arguments (given 1, expected 0)" error.  Here's a screenshot of the error I was getting before making this change:

screen shot 2017-03-08 at 11 04 11 am

**Comment by glebm** [comment]
OK, please add a comment with an explanation and point to the line in the devise_security_extensions gem where it happens.

Also, all Ruby code is formatted and linted by rubocop, and it must report no issues. See https://github.com/thredded/thredded#ruby.

**Comment by pak9rabid** [comment]
The requested changes have been made

**Comment by glebm** [comment]
After considering it a bit, I've figured that the most robust way to solve it is to avoid conflicts altogether, and renamed `signed_in?` to `thredded_signed_in?` in #543.

We had done a similar change in the past, renaming `current_user` to `thredded_current_user` in #176.

**Comment by glebm** [comment]
This should now be fixed on master!

**Comment by pak9rabid** [comment]
Awesome, I appreciate yall's responsiveness on this!

**Comment by pak9rabid** [comment]
Tested it out, works great.  Thanks!

**Pull request closed without merging**
