### PR TITLE
[SMB] Seeds users with preferences for dummy app

### LINKED ISSUE #218: Error when creating new private message
Not sure if it's just how the dummy app is initialized but when creating a new private topic I get the following

undefined method `notify_on_message?' for #<Thredded::UserPreference:0x007fb1a0726740>

### PR DESCRIPTION
**Pull request by TheDudeWithTheThing**
Fixes #218

### CODE REVIEW

**Comment by jayroh** [comment]
Beautiful! Thank you Shaun! 🎉

**Comment by glebm** [comment]
This shouldn't be necessary. Thredded only creates a Preference record once the user changes the preferences. By default, there is no preference record, so this doesn't represent the data a real app would have. IMO this should be reverted or only applied to a subset of the users.

**Comment by TheDudeWithTheThing** [comment]
REVERT THIS @jayroh 

I'll confirm this is fixed / broken with the latest version post revert.

**Comment by jayroh** [comment]
Whoops. Ok. We'll get this situated shortly

**Comment by jayroh** [comment]
Just pushed a commit up that effectively reverts this. No big deal

**Comment by TheDudeWithTheThing** [comment]
sorry to all parties involved!

**Comment by jayroh** [comment]
I wonder what Vince has to say about all this ... paging Vince ...

**Pull request merged**
