### PR TITLE
Readme: Update user profile page instructions

### PR DESCRIPTION
**Pull request by glebm**
Updates the instructions to use the Rails 5 render-anywhere method.

@jayroh @timdiggins What do you think?

### CODE REVIEW

**Comment by jayroh** [comment]
LGTM, man! 👍

**Comment by timdiggins** [comment]
@glebm what's the benefit of using this method rather than previous way?  If I understand correctly this feature was created for rendering outside controllers https://github.com/rails/rails/pull/18546

(I'm successfully using the previously documented mechanism)

**Comment by glebm** [comment]
@timdiggins The previous mechanism required the user to `include Thredded::ApplicationHelper` into the controller that render the user's profile page, which had a high likelihood of name clashes with `main_app`, as we use helpers such as `user_link`.

**Comment by glebm** [comment]
@timdiggins and yeah, this was created for rendering outside of the controllers and fakes the request environment. But it's OK I guess as we don't use the request environment when rendering these partials.

**Pull request merged**
