### PR TITLE
Namespace MessageBoard in post.rb

### PR DESCRIPTION
**Pull request by tiii**

### CODE REVIEW

**Comment by jayroh** [comment]
Was this causing a problem somewhere?

**Comment by tiii** [comment]
Not in my case - but for consistency reasons I would suggest you prefix all thredded models. And it will cause trouble if you have an own Messageboard model in your app.

**Comment by tiii** [comment]
I guess i'll close this again, since I can't reproduce it.

**Comment by jayroh** [comment]
Nah I think it's still worth pulling in. I asked out of curiosity in the off chance it was causing issues 😁

**Comment by jayroh** [comment]
Feel free to reopen if you'd like

**Comment by tiii** [comment]
I just realized the other relations have different names and rails does namespaced model lookup in relations. No need to change this :ok_hand:

**Comment by jayroh** [comment]
Cool. Thanks for the added context :)

On Wed, Dec 6, 2017 at 9:07 AM, Titus Ramczykowski <notifications@github.com

**Pull request closed without merging**
