### PR TITLE
Run demo on heroku

### PR DESCRIPTION
**Pull request by jayroh**
Sort of.

* Assets aren't being served.
* Errors aren't showing up in the logs (bizarre as hell)

Otherwise things look like they're working.

@glebm @TheDudeWithTheThing - you should have emails with heroku credentials and repo information.

### CODE REVIEW

**Comment by jayroh** [comment]
I'm so annoyed that I can't get assets to serve .... ugh.

💤

**Comment by glebm** [comment]
I'll have a look. We can probably just have Rails serve the assets and cache them with CloudFront.

**Comment by glebm** [comment]
Got the assets and logging working.

1. Cleaned up the config, moved all heroku stuff into heroku-named files (heroku.gemfile, puma.heroku.rb, etc).
2. Switched to a custom buildpack that uses heroku.gemfile instead of Gemfile.
3. Squashed and rebased all the commits.

**Comment by glebm** [comment]
We should put CloudFront in front of it, so that assets are automatically served from a CDN.

**Comment by glebm** [comment]
Also runs Rails 5 now

**Comment by jayroh** [comment]
@glebm! THANK YOU. Honestly this was driving me crazy and I couldn't sleep. Thank you for fixing this up.

For future reference I'm going to put the link to the buildpack here so anyone looking (including myself) can find it - https://github.com/glebm/heroku-buildpack-ruby  👈  that is very handy

**Comment by jayroh** [comment]
```ruby
config.public_file_server.enabled = true
```

Was this the part needed to get the assets served? Because oh my god this was driving me batshit insane

**Comment by jayroh** [comment]
Going to merge this in and spin up cloudflare on top of it.

Since I have a good number of dependencies for thredded.com at it's current nameserver I'll hose this under thredded.org - which makes some sense, as it could house further properties under that (blog, etc)

**Comment by glebm** [comment]
> ```ruby
> config.public_file_server.enabled = true
> ```
>
> Was this the part needed to get the assets served? Because oh my god this was driving me batshit insane

Yeah, Heroku doesn't have a file server, so we need Rails to do that instead. This is a Rails 5 thing, it is the same as `config.serve_static_files` in Rails 4. While serving files from Rails is slow, Cloudflare will be in front of it and it will cache the assets, and serve them from the CloudFlare CDN.

**Comment by jayroh** [comment]
After poking around a little bit, it looks like there are some AR / db pool
issues?

> FATAL -- : ActiveRecord::ConnectionTimeoutError (could not obtain a
connection from the pool within
5.000 seconds (waited 5.002 seconds); all pooled connections were in use):

Seeing this quite a bit after clicking around the app for a few minutes.

And then I provisioned New Relic and for some reason can't get that to
report stats ... even after 20 minutes or so. Hmm.

I was optimistic and thought it would "just work" and committed what new
relic needs to master, so they're in there even though things aren't
working. Vexing, I tell you :/

On Sat, Apr 16, 2016 at 10:28 AM, Gleb Mazovetskiy <notifications@github.com

**Comment by glebm** [comment]
The pool size must be at least workers x threads.

**Comment by glebm** [comment]
I'll fix it

**Comment by glebm** [comment]
OK, this should fix the pool size error https://github.com/thredded/thredded/commit/247fe96309c815757414e862ba00192ebcc036e6

**Comment by jayroh** [comment]
Can I steal/kidnap you and make you work with me everywhere.

ha ha just kidding. sort of. haha ... ok not really.

(thank you Gleb)

**Pull request merged**
