### PR TITLE
[JRO] img's shouldn't be larger than container div

### PR DESCRIPTION
**Pull request by jayroh**
Fixes issue #187

### CODE REVIEW

**Comment by glebm** [comment]
As per how we do it in Bootstrap, it should also have `height: auto`: https://github.com/twbs/bootstrap/blob/v4-dev/scss/mixins/_image.scss#L10-L14

**Comment by jayroh** [comment]
Good idea - will make that change and squash. Be right back

**Comment by jayroh** [comment]
> how we do it in Bootstrap

Some day ... I'm buying you a beer and we're debating the merits of bootstrap.

**Comment by glebm** [comment]
:+1: :smile:

**Pull request merged**
